---
- name: Enable intranet services
  hosts: servera.lab.example.com
  become: yes

  tasks:
    - name: Install httpd service
      yum:
        name: 
          - httpd
          - firewalld
        state: latest

# note the indent position of 'with_items:'
    - name: test with_items
      debug:
        msg: "item = {{ item }}"
      with_items:
        - firewalld
        - httpd

# note the indenting position of 'with_items:'
    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - firewalld
        - httpd

    - name: firewall permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
