---
- name: Enable intranet services
  hosts: servera.lab.example.com
  become: yes

  tasks:
    - name: Install httpd service
      yum:
        name: 
          - httpd
          - firewalld
        state: latest
    
    - name: firewalld enabled and started
      service:
        name: firewalld
        state: started
        enabled: true
    
    - name: firewall permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        state: started
        enabled: true

    - name: test html page is installed
      copy:
        content: "welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html

- name: Test intranet web server
  hosts: localhost
  become: no

  tasks:
    - name: connect to intranet web server
      uri:
        url: http://servera.lab.example.com
        status_code: 200

