---
- name: testing
  hosts: servera.lab.example.com
  become: false
  vars:
    user: joe
  vars_files:
    - vars/data.yml

  tasks:
    - name: display the value of {{ user }}
      debug:
        msg: >
          user = "{{ user }}"
          pass = "{{ password }}"
